### ISSUE TITLE
一打开网页就进黑名单

### ISSUE THREAD

**Issue by haohetao** [limithit/ngx_dynamic_limit_req_module#1]
无论怎么设置都是这样

**Comment by haohetao** [comment]
```
 #dynamic_limit_req_zone '$binary_remote_addr-$request_uri' zone=one:50m rate=5r/s redis=redis block_second=500;
```
```
#dynamic_limit_req_zone $binary_remote_addr zone=two:10m rate=50r/s redis=redis block_second=500;
```
```
 #dynamic_limit_req_zone $binary_remote_addr zone=three:10m rate=200r/m redis=redis block_second=3600;
```
```
 #dynamic_limit_req zone=one burst=5 nodelay;
#dynamic_limit_req zone=two burst=25 nodelay;
#dynamic_limit_req zone=three burst=100 nodelay;
#dynamic_limit_req_status 403;
```
配置是注释了，这三条规则只有单独使用第2条可以，其它两条加上就403，把第2条复制一下，改下Zone也会403

**Comment by limithit** [comment]
你根本不知道burst的意思吧，你可以把burst加大到50算是正常的，你不太会，就不要搞太复杂了，先一条规则来

**Comment by limithit** [comment]
```dynamic_limit_req_zone $binary_remote_addr zone=two:10m rate=50r/s redis=redis block_second=500;```
```
dynamic_limit_req zone=two burst=5 nodelay;
```
虽然 rate=50r/s设置的是每秒50个请求，但是你的burst设置是5个,那么当你每秒达到5个请求，就会被拦截
，你可以设置成
```
dynamic_limit_req zone=two burst=50 nodelay;
```
就可以每秒50个请求了

**Comment by haohetao** [comment]
我只要点一下就进黑名单了，不过我可以加大burst或去掉burst试试

**Comment by haohetao** [comment]
`    #dynamic_limit_req_zone '$binary_remote_addr-$request_uri' zone=one:50m rate=5r/s redis=redis block_second=500;
    dynamic_limit_req_zone $binary_remote_addr zone=two:10m rate=50r/s redis=redis block_second=500;
    dynamic_limit_req_zone $binary_remote_addr zone=three:10m rate=100r/m redis=redis block_second=3600;
    #dynamic_limit_req zone=one burst=10 nodelay;
	dynamic_limit_req zone=two;
	dynamic_limit_req zone=three;
	dynamic_limit_req_status 403;`
现在这样配置还是进黑名单，主要第一次访问就是403
附件是完整的nginx.conf
[nginx.zip](https://github.com/limithit/ngx_dynamic_limit_req_module/files/2653287/nginx.zip)

**Comment by haohetao** [comment]
我尝试把dynamic_limit_req加到server配置还是一样403

**Comment by limithit** [comment]
你需要知道自己nginx并发到底是多少，才能设置合理区间，200r/m这是每分钟200个请求，但你配置文件都是错的

**Comment by haohetao** [comment]
只有我一个IP访问，只是测试站点，并没有公开

**Comment by haohetao** [comment]
项目上线后会跟据情况调整，你说配置文件是错的是指哪个地方

**Comment by limithit** [comment]
```
	dynamic_limit_req zone=two;
	dynamic_limit_req zone=three;
```
正确的应应该是这样
```
dynamic_limit_req zone=two burst=50 nodelay;
dynamic_limit_req zone=three burst=50 nodelay;
```

**Comment by limithit** [comment]
你可以nginx -t下先

**Comment by haohetao** [comment]
root@8d554986685a:/# /usr/local/nginx/sbin/nginx -t
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful

**Comment by limithit** [comment]
我帮你配置吧，讲不明白跟你

**Comment by limithit** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmny8gsq3CvNeewh7OTqfDpCcAKDBxeULxMLgQFtFhWR9LApzH4B1MRATQJMSammNxxOSM0oLi1AOFJmITK3BNoNOeayqnFSraTmkg6Yd1+ykRXbnunO6gdFh7EJyk67vun8fjEIHOC40w8DO9Efu3T7kD3dHPs+5uBBfgsOIU7wDNEMzRN1EhdstvxYbwOcLsw7KboDiJTozq12Ln7mRswR7J2yMmWXo+8Xp/3Zu0MFE2UAHW6qS7BY2dDUNZFyLoI7uspUJCnQsGgvfO/b2vVoCOfu+fwDDQLe6Tyv/GMmAzoq1ViayR/9zWsdDqcYF9fdU7SXwcBtTI+9eVqTjN limit@limitdeMacBook-Pro.local

**Comment by haohetao** [comment]
这样写一样的问题，我只是把burst去掉了

**Comment by haohetao** [comment]
#dynamic_limit_req_zone '$binary_remote_addr-$request_uri' zone=one:50m rate=5r/s redis=redis block_second=500;
    dynamic_limit_req_zone $binary_remote_addr zone=two:10m rate=50r/s redis=redis block_second=500;
    dynamic_limit_req_zone $binary_remote_addr zone=three:10m rate=100r/m redis=redis block_second=3600;
    #dynamic_limit_req zone=one burst=10 nodelay;
	dynamic_limit_req zone=two burst=100 nodelay;
	dynamic_limit_req zone=three burst=100 nodelay;

**Comment by haohetao** [comment]
nginx是在Docker环境中运行的

**Comment by haohetao** [comment]
你的ssh key呢？

**Comment by limithit** [comment]
> 你的ssh key呢？

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmny8gsq3CvNeewh7OTqfDpCcAKDBxeULxMLgQFtFhWR9LApzH4B1MRATQJMSammNxxOSM0oLi1AOFJmITK3BNoNOeayqnFSraTmkg6Yd1+ykRXbnunO6gdFh7EJyk67vun8fjEIHOC40w8DO9Efu3T7kD3dHPs+5uBBfgsOIU7wDNEMzRN1EhdstvxYbwOcLsw7KboDiJTozq12Ln7mRswR7J2yMmWXo+8Xp/3Zu0MFE2UAHW6qS7BY2dDUNZFyLoI7uspUJCnQsGgvfO/b2vVoCOfu+fwDDQLe6Tyv/GMmAzoq1ViayR/9zWsdDqcYF9fdU7SXwcBtTI+9eVqTjN limit@limitdeMacBook-Pro.local

**Comment by haohetao** [comment]
用户名是ubuntu

**Comment by limithit** [comment]
账号

**Comment by limithit** [comment]
docker进不去
```ubuntu@ip-172-31-31-33:~$ docker-compose exec web /bin/bash
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ubuntu@ip-172-31-31-33:~$ 
```

**Comment by haohetao** [comment]
cd epserver

**Comment by limithit** [comment]
你重新试下，两个条件冲突，你参考我 README.md配置，我是加了别的条件的

**Comment by haohetao** [comment]
只能一个条件？

**Comment by limithit** [comment]
你好好看我写的吧，我是不同的url

**Comment by haohetao** [comment]
那就是同一URL只能用一个条件？

**Comment by haohetao** [comment]
我知道你写的，但是需求不一样，我也不能完全照抄呀

**Comment by haohetao** [comment]
我之前只用一个条件有时候也是能成功的

**Comment by limithit** [comment]
它会优先最接近它的条件，比如，burst=5, burst=3它会优先 burst=3的
```
worker_processes  2;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    
    dynamic_limit_req_zone $binary_remote_addr zone=one:10m rate=100r/s redis=127.0.0.1 block_second=300;
    dynamic_limit_req_zone $binary_remote_addr zone=two:10m rate=50r/s redis=127.0.0.1 block_second=600;
    dynamic_limit_req_zone $binary_remote_addr zone=sms:5m rate=5r/m redis=127.0.0.1 block_second=1800;
    
    
    server {
        listen       80;
        server_name  localhost;
        location / {
            
            if ($http_x_forwarded_host) {
             return 400;
            }
            root   html;
            index  index.html index.htm;
            dynamic_limit_req zone=one burst=100 nodelay;
            dynamic_limit_req_status 403;
        }
        error_page   403 500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
    server {
        listen       80;
        server_name  localhost2;
        location / {
            root   html;
            index  index.html index.htm; 
            
                set $flag 0;
               if ($document_uri ~* "regist"){
                  set $flag "${flag}1";
                    }
              if ($request_method = POST ) {
                    set $flag "${flag}2";
                      }
                  if ($flag = "012"){
                  dynamic_limit_req zone=sms burst=3 nodelay;
                  dynamic_limit_req_status 403;
                  } 
                  if ($document_uri ~* "getSmsVerifyCode.do"){
                  dynamic_limit_req zone=sms burst=5 nodelay;
                  dynamic_limit_req_status 444;
            }

            dynamic_limit_req zone=two burst=50 nodelay;
            dynamic_limit_req_status 403;
        }
        error_page   403 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
```
请参照这个来，我不再答复了

**Comment by limithit** [comment]
第一个server是全网拦截，第二个sever只拦截指定的接口，足够适用任何类型的业务

**Comment by haohetao** [comment]
这不是哪个优先的问题，而是一个url两个条件都命中的话直接就403，第一次就403

**Comment by limithit** [comment]
> 这不是哪个优先的问题，而是一个url两个条件都命中的话直接就403，第一次就403

我的意思是不需要一个url多个条件

**Comment by haohetao** [comment]
全网拦截和指定url在一个server中也不能同时用是吧？

**Comment by limithit** [comment]
至少我没试过，我只有http 和server中用
比如这样
http
```
  dynamic_limit_req_zone $binary_remote_addr zone=one:10m rate=100r/s redis=127.0.0.1 block_second=600;
      dynamic_limit_req zone=one burst=80 nodelay;
      dynamic_limit_req_status 403
```
server{
....
   dynamic_limit_req zone=one burst=60 nodelay;
      dynamic_limit_req_status 403
}
```

**Comment by haohetao** [comment]
我先试试

**Comment by haohetao** [comment]
同一个配置区段只能写一个条件
我可以在http写一个，server写一个,location写一个
这样写3个可以
