### ISSUE TITLE
nginx -s reload出现directive dynamic_limit_req_redis is duplicate

### ISSUE THREAD

**Issue by haohetao** [limithit/ngx_dynamic_limit_req_module#14]
还会导致reload不生效
restart是正常的，而且dynamic_limit_req_redis只写了一个

**Comment by limithit** [comment]
你最好贴出你的conf文件，另外我修复了另一个问题，也许会对你有帮助，当redis关闭时需要nginx restart 才可以再次连接的，reload的确无法生效

**Comment by limithit** [comment]
好吧不需要贴了，已经重现了

**Comment by limithit** [comment]
已修复
