### ISSUE TITLE
Not working and no log messages

### ISSUE THREAD

**Issue by ziemowitp** [limithit/ngx_dynamic_limit_req_module#17]
Hi,

I compiled the module with nginx 1.22 and after some tests, it doesn't appear to be working.  Am I supposed to be getting anything in the logs?  I purposely configured it with a non existant Redis at 127.0.0.1 and nothing in error messages.

Here is my test configuration:

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    
    dynamic_limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s redis=127.0.0.1 block_second=300;
   
    server {
        listen       80;

        location / {
            return 200 "$remote_addr";
            dynamic_limit_req zone=one burst=1 nodelay;
            dynamic_limit_req_status 403;
        }
    }

**Comment by limithit** [comment]
Comment out this line  ` #return 200 "$remote_addr";`

**Comment by ziemowitp** [comment]
I tried removing the line and then this configuration:

server {
        listen 80;
        access_log /var/log/nginx/access.log;

        root /srv;
        index index.html;

        autoindex on;

        location "/a" {
            dynamic_limit_req zone=one burst=1 nodelay;
            dynamic_limit_req_status 429;
        }
    }

Still doesn't appear to be working.  No errors in the logs.  The only thing I see is the syntax validation appears to work.

**Comment by limithit** [comment]
location / {
        dynamic_limit_req zone=one burst=1 nodelay;
        dynamic_limit_req_status 429;
    }

**Comment by limithit** [comment]
You first test the [nginx.conf](https://github.com/limithit/ngx_dynamic_limit_req_module/blob/master/README.md) configuration I gave you, and if it doesn't work, I'll investigate why!

**Comment by ziemowitp** [comment]
I tried the example configuration too but it didn't appear to work; however, I started over from scratch and it worked.  

Now is it possible to use the module with Redis on a non local machine?  Something like this:

dynamic_limit_req_zone $binary_remote_addr zone=sms:5m rate=5r/m redis=10.17.99.51 block_second=300;

**Comment by limithit** [comment]
Yes, it is.
