### ISSUE TITLE
希望加入Redis数据库选择的配置

### ISSUE THREAD

**Issue by haohetao** [limithit/ngx_dynamic_limit_req_module#2]
现在默认就进0和1数据库了，但是这两个数据库里还有其它数据

**Comment by limithit** [comment]
这个建议你单独一个redis，不考虑加入库的选择没有太大意义，还有你的说的一打网页就进黑名单，我需要你贴出你的nginx.conf配置

**Comment by haohetao** [comment]
好的，如果用单独的redis的话端口号怎么写

**Comment by limithit** [comment]
我没有加端口的选择，你可改下源码把6379改成你想要的端口，或者其他项目改端口，这个就默认的

**Comment by haohetao** [comment]
ok

**Comment by ZTzha** [comment]
@haohetao 修改源码,重新编译就可以了...

` if (rc && strncmp((char *) Host, "127.0.0.1", 9) != 0) {
                        if (!c->err) {
                                reply = redisCommand(c, "SELECT 9");
                                reply = redisCommand(c, "GET white%s", Host);
                                if (reply->str == NULL) {
                                        reply = redisCommand(c, "SELECT 9");
                                        reply = redisCommand(c, "SETEX %s %s %s", Host,
                                                        block_second, Host);
                                        /* Increase the history record  */
                                        reply = redisCommand(c, "SELECT 8");
                                        reply = redisCommand(c, "SET %s %s", Host, Host);
                                        /* reply = redisCommand(c, "SELECT 9"); */
                                        /* Increase the history record */
                                }
                        }        
                }`
