### ISSUE TITLE
在源站使用CDN的情况下，如何实现block

### ISSUE THREAD

**Issue by zh9210** [limithit/ngx_dynamic_limit_req_module#4]
map $http_x_forwarded_for  $clientRealIp {
        ~^(?P<firstAddr>[0-9\.]+),?.*$  $firstAddr;
        }
.........
dynamic_limit_req_zone $clientRealIp zone=one:10m rate=10r/m redis=127.0.0.1 block_second=600;
..........
dynamic_limit_req burst=10 zone=one nodelay;
dynamic_limit_req_status 429;
===============================
Nginx 日志格式：
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      '"$upstream_response_time" "$upstream_addr"';

===============================

<img width="939" alt="errorlog" src="https://user-images.githubusercontent.com/29391685/54628278-29f2fa80-4ab0-11e9-9686-00682ddf8c8d.png">
<img width="946" alt="accesslog" src="https://user-images.githubusercontent.com/29391685/54628515-b00f4100-4ab0-11e9-9234-4d90f348f20d.png">

限制的配置如上，由于前端使用了CDN，$remote_addr 是CDN的IP，$http_x_forwarded_for 是客户端真实IP，如上配置，测试下来发现，被加到redis黑名单的 地址会是 CDN的IP，也就是$remote_addr 地址，这个怎么解决？

**Comment by limithit** [comment]
$http_x_forwarded_for 太容易伪造,所以并没有考虑此种情况,目前不支持cdn,
curl -H "X-Forwarded-For:192.168.0.1, 192.168.0.2" http://node3.nginx.org

**Comment by limithit** [comment]
http {
     .........
     set_real_ip_from 192.168.16.0/24;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    #dynamic_limit_req_zone $binary_remote_addr zone=one:10m rate=100r/s redis=127.0.0.1 block_second=600;
    dynamic_limit_req_zone $http_x_forwarded_for zone=one:10m rate=1r/m redis=127.0.0.1 block_second=600;
    dynamic_limit_req zone=one burst=1 nodelay;
    dynamic_limit_req_status 403;

........
 }


这种配置方式支持CDN, 需要启用--with-http_realip_module模块

**Comment by zh9210** [comment]
好的，多谢。我好像也搜到过，原理是将X-Forwarded-For 传递给$remote_addr,这个我今天测试下，看是否有效再来感谢！
