### ISSUE TITLE
 RedisPushIptables 与 ngx_dynamic_limit_req_module对接问题

### ISSUE THREAD

**Issue by w796933** [limithit/ngx_dynamic_limit_req_module#5]
你好， 请问我安装好  ngx_dynamic_limit_req_module 和  RedisPushIptables  ，默认情况下  ngx_dynamic_limit_req_module 模块就可以 调用  RedisPushIptables的ipset来 达到屏蔽攻击的IP？ 还需要额外配置吗？

**Comment by limithit** [comment]
@w796933 需要另外配置

**Comment by w796933** [comment]
可以指点下？ 有对接配置文档吗？

**Comment by limithit** [comment]
```
if (rc && strncmp((char *) Host, "127.0.0.1", 9) != 0) {
			if (!c->err) {
				reply = redisCommand(c, "GET white%s", Host);
				if (reply->str == NULL) {
				//	reply = redisCommand(c, "SETEX %s %s %s", Host,
				//			block_second, Host);
	                        reply = redisCommand(c, "drop_insert %s", Host);
					/* Increase the history record  */
					reply = redisCommand(c, "SELECT 1");
					reply = redisCommand(c, "SET %s %s", Host, Host);
					reply = redisCommand(c, "SELECT 0");
					/* Increase the history record */
				}
			}
		}
```

**Comment by limithit** [comment]
```
          reply = redisCommand(c, "drop_insert %s", Host); 
  OR
          reply = redisCommand(c,"ttl_drop_insert %s %s", Host, block_second);
```

**Comment by w796933** [comment]
nginx  链接 redis   会损耗多少性能？

**Comment by limithit** [comment]
小到可以忽略

**Comment by w796933** [comment]
如果改成加白名单到 IP 到里面。  怎么改动代码？

**Comment by limithit** [comment]
白名单本身就支持不需要改，详细参考这个说明https://github.com/limithit/ngx_dynamic_limit_req_module#black-and-white-list

**Comment by w796933** [comment]
模块的白名单  添加 ：  redis-cli set white192.168.1.1 192.168.1.1

RedisPushIptables 的添加白名单  redis-cli ACCEPT_INSERT 192.168.1.1
2者都添加白名单，会不会造成冲突。
还是说 ngx_dynamic_limit_req_module 模块添加了白名单IP 。是可以直接 到 RedisPushIptables  里面的？

**Comment by limithit** [comment]
不会冲突

**Comment by w796933** [comment]
好的。非常感谢。 非常实用的模块。

**Comment by w796933** [comment]
你好，
ipset create block_ip hash:ip  hashsize 4096 maxelem 10000000
iptables -I INPUT -m set --match-set block_ip src -j DROP

我ipset 没有设置 time out . 

redis-cli TTL_DROP_INSERT 1.1.1.1  60  
ttl drop 设置60秒超时，  60秒后 redis  里面 1.1.1.1 IP被删除了。但是ipset list 规则列表中 还有 1.1.1.1 被屏蔽中。并没有释放， 这个是设置上的问题吗？

**Comment by limithit** [comment]
ttl_iptables守护进程启了吗 @w796933

**Comment by limithit** [comment]
make CFLAGS=-DWITH_IPSET 是这个编译选项吗

**Comment by w796933** [comment]
ttl_iptables守护进程确定启动了。 make CFLAGS=-DWITH_IPSET  确定是这个编译选项的。 
redis-cli TTL_DROP_INSERT 1.1.1.1 60   执行这个命令后 IP是添加到 ipset 和redis 的。 只不过 60秒后 redis ip里面的IP没了， 但是ipset 没释放。

**Comment by w796933** [comment]
另外我测试中。 直接用iptables  屏蔽IP    /var/log/ttl_iptables.log  日志是会记录的， 但是如果用 ipset 屏蔽IP，  /var/log/ttl_iptables.log 日志并没有记录。

**Comment by limithit** [comment]
那应该是ipset的路径找不到

**Comment by w796933** [comment]
ipset  我在Ubuntu下 直接 apt-get install 安装的，添加ipset 规则是成功的，但是删除不成功， 应该不是路径问题吧？

**Comment by limithit** [comment]
你慢慢查吧，我开发的时候都测过的

**Comment by limithit** [comment]
Debian Centos

**Comment by w796933** [comment]
请问如何捐赠此项目， 浪费你那么多时间。
刚刚测试了 centos  7  。 一样的情况。 
/var/log/ttl_iptables.log 日志没输出，  ipset  ttl  超时后， ipset  屏蔽的IP，不会释放，
请问如何指定ipset ？
添加ipset 规则是成功的.

**Comment by limithit** [comment]
你个人就不用捐了，开源就是给人用的，不用也没价值，你要是方便给我个账号我来调试下

**Comment by w796933** [comment]
服务器信息，已发送到你邮箱。

**Comment by limithit** [comment]
notify-keyspace-events Ex 这个要设置，还有就是重新编译ttl_iptables,要把之前的删除 @w796933 已经可以用了
